version: '3.8'

services:
    explorer:
        environment:
            - DJANGO_FILE_STORAGE=storages.backends.s3boto3.S3Boto3Storage
            - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME:?S3 bucket name unset}
            - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL:?S3 endpoint url unset}
            - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME:?S3 region name unset}
        secrets:
            - s3_access_key_id
            - s3_secret_access_key

secrets:
    s3_access_key_id:
        file: ./secrets/s3_access_key_id
    s3_secret_access_key:
        file: ./secrets/s3_secret_access_key
